spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: oracle:thin:@ADMIN?TNS_ADMIN=./src/main/resources/wallet
    username: ADMIN
    password: Kosadb2team!
server:
  port: 8081